baseURL = "https://starmaex.com/"
languageCode = "en-us"
title = "Starmaex Games"
theme = "dopetrope"

[params.portfolio]
    title = "My Portfolio"
    foldername = "portfolio"
    findoutmoretext = "Find out more"

[params.blog]
    title = "The Blog"
    viewalltext = "View All"
    foldername = "blog"

[params.settings]
    googleanalytics = "UA-113904582-1"
    disqus = "hugo-dopetrope"